--カテゴリー
INSERT INTO categories(name) VALUES('料理');
INSERT INTO categories(name) VALUES('野菜各種');
INSERT INTO categories(name) VALUES('社食');
INSERT INTO categories(name) VALUES('Myメニュー');

--仮ユーザ
INSERT INTO users(name,gender,birthyear,birthmonth,birthday,tel,email,password) VALUES('A', '男性',1999,01,01,'07011112222','A','A');

--必要な摂取量
--vitamin(μg), mineral(mg)で計算、Na = 5000mgと仮定
INSERT INTO intake(range, gender, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES('18～29','男性',2650,331,65,74,7009,9640);
INSERT INTO intake(range, gender, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES('30～49','男性',2700,338,65,75,7059,9620);
INSERT INTO intake(range, gender, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES('50～64','男性',2600,325,65,72,8059,9620);
INSERT INTO intake(range, gender, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES('65～74','男性',2400,300,65,67,8009,9600);
INSERT INTO intake(range, gender, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES('18～29','女性',2000,250,50,56,5809,8720);
INSERT INTO intake(range, gender, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES('30～49','女性',2050,256,50,57,6359,8740);
INSERT INTO intake(range, gender, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES('50～64','女性',1950,244,50,54,6859,8740);
INSERT INTO intake(range, gender, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES('65～74','女性',1850,206,50,51,7359,8730);

INSERT INTO foods(category_id, name, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES(1,'食パン',160.0,46.6,9.0,4.2,502.0,669.1);
INSERT INTO foods(category_id, name, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES(1,'アイスクリーム',180.0,3.9,1.0,8.0,0.0,0.0);
INSERT INTO foods(category_id, name, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES(1,'回鍋肉',250.0,9.0,15.2,8.0,102.0,69.1);
INSERT INTO foods(category_id, name, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES(1,'サイコロステーキ',250.0,9.0,15.2,8.0,102.0,1619.1);
INSERT INTO foods(category_id, name, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES(1,'餃子',230.0,9.0,15.2,8.0,102.0,1691.1);
INSERT INTO foods(category_id, name, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES(1,'コーンポタージュ',190.0,6.0,4.6,5.0,72.0,1619.7);
INSERT INTO foods(category_id, name, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES(1,'豆腐チゲ',190.0,6.0,4.6,5.0,72.0,1691.7);
INSERT INTO foods(category_id, name, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES(1,'コンソメスープ',190.0,6.0,4.6,5.0,72.0,1691.7);
INSERT INTO foods(category_id, name, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES(1,'ミネストローネスープ',190.0,6.0,4.6,5.0,72.0,691.7);
INSERT INTO foods(category_id, name, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES(1,'キンメダイの煮つけ',280.0,16.6,9.0,4.2,212.5,857.2);
INSERT INTO foods(category_id, name, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES(1,'キスの天ぷら',280.0,16.6,9.0,4.2,212.5,857.2);
INSERT INTO foods(category_id, name, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES(1,'シラスの踊り食い',280.0,16.6,9.0,4.2,212.5,857.2);
INSERT INTO foods(category_id, name, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES(1,'イワナの塩焼き',280.0,16.6,9.0,4.2,212.5,1857.2);
INSERT INTO foods(category_id, name, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES(1,'中華丼',510.4,36.6,10.0,4.2,112.5,757.2);
INSERT INTO foods(category_id, name, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES(1,'チャーシューチャーハン',610.4,36.6,10.0,4.2,112.5,1457.2);
INSERT INTO foods(category_id, name, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES(1,'親子丼',510.4,36.6,10.0,4.2,112.5,457.2);
INSERT INTO foods(category_id, name, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES(1,'ポテトサラダ',160.7,8.6,6.0,2.3,1162.2,757.2);
INSERT INTO foods(category_id, name, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES(1,'コロッケ',160.7,8.6,6.0,2.3,162.2,757.2);
INSERT INTO foods(category_id, name, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES(1,'レバーの焼き鳥',160.7,8.6,6.0,2.3,162.2,757.2);
INSERT INTO foods(category_id, name, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES(1,'茄子の揚げびたし',160.7,8.6,6.0,2.3,162.2,757.2);

INSERT INTO foods(category_id, name, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES(2,'トマト',40.1,2.1,0.0,0.3,5612.4,917.8);
INSERT INTO foods(category_id, name, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES(2,'かぼちゃ',40.1,2.1,0.0,0.3,5612.4,917.8);
INSERT INTO foods(category_id, name, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES(2,'ほうれん草',40.1,2.1,0.0,0.3,1262.4,197.8);
INSERT INTO foods(category_id, name, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES(2,'なす',40.1,2.1,0.0,0.3,562.4,971.8);
INSERT INTO foods(category_id, name, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES(2,'きゅうり',40.1,2.1,0.0,0.3,562.4,917.8);
INSERT INTO foods(category_id, name, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES(2,'チンゲン菜',40.1,2.1,0.0,0.3,562.4,917.8);
INSERT INTO foods(category_id, name, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES(2,'舞茸',40.1,2.1,0.0,0.3,562.4,917.8);
INSERT INTO foods(category_id, name, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES(2,'しめじ',40.1,2.1,0.0,0.3,562.4,917.8);
INSERT INTO foods(category_id, name, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES(2,'えのき',40.1,2.1,0.0,0.3,562.4,917.8);
INSERT INTO foods(category_id, name, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES(2,'大根',40.1,2.1,0.0,0.3,562.4,917.8);
INSERT INTO foods(category_id, name, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES(2,'キャベツ',40.1,2.1,0.0,0.3,562.4,917.8);
INSERT INTO foods(category_id, name, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES(2,'ごぼう',40.1,2.1,0.0,0.3,562.4,917.8);
INSERT INTO foods(category_id, name, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES(2,'ニンジン',40.1,2.1,0.0,0.3,562.4,917.8);
INSERT INTO foods(category_id, name, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES(2,'グレープフルーツ',50.7,2.1,0.5,0.3,8132.5,1124.8);
INSERT INTO foods(category_id, name, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES(2,'さくらんぼ',50.7,2.1,0.5,0.3,8132.5,1124.8);
INSERT INTO foods(category_id, name, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES(2,'メロン',50.7,2.1,0.5,0.3,832.15,1214.8);
INSERT INTO foods(category_id, name, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES(2,'すいか',50.7,2.1,0.5,0.3,8321.5,1214.8);
INSERT INTO foods(category_id, name, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES(2,'バナナ',50.7,2.1,0.5,0.3,8312.5,1124.8);

INSERT INTO foods(category_id, name, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES(3,'唐揚げとふわふわオムレツ',500.0,10.1,18.0,7.3,8312.5,2124.8);
INSERT INTO foods(category_id, name, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES(3,'さばの塩焼き',500.0,10.1,18.0,7.3,8312.5,2124.8);
INSERT INTO foods(category_id, name, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES(3,'しょうが焼き(目玉焼き付き)',500.0,10.1,18.0,7.3,8312.5,2124.8);
INSERT INTO foods(category_id, name, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES(3,'ビーフカレー',500.0,10.1,18.0,7.3,8312.5,2124.8);
INSERT INTO foods(category_id, name, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES(3,'網焼き牛カルビ皿',500.0,10.1,18.0,7.3,8312.5,2124.8);
INSERT INTO foods(category_id, name, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES(3,'さばの塩麴焼き',500.0,10.1,18.0,7.3,8312.5,2124.8);
INSERT INTO foods(category_id, name, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES(3,'彩り野菜の焼き鳥丼',500.0,10.1,18.0,7.3,8312.5,2124.8);
INSERT INTO foods(category_id, name, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES(3,'根菜とナスのごろっと野菜カレー',500.0,10.1,18.0,7.3,8312.5,2124.8);
INSERT INTO foods(category_id, name, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES(3,'和風餡かけハンバーグ',500.0,10.1,18.0,7.3,8312.5,2124.8);
INSERT INTO foods(category_id, name, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES(3,'さばの味噌煮',500.0,10.1,18.0,7.3,8312.5,2124.8);
INSERT INTO foods(category_id, name, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES(3,'親子丼',500.0,10.1,18.0,7.3,8312.5,2124.8);
INSERT INTO foods(category_id, name, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES(3,'バターチキンカレー',500.0,10.1,18.0,7.3,8312.5,2124.8);
INSERT INTO foods(category_id, name, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES(3,'もち豚のしょうが焼き',500.0,10.1,18.0,7.3,8312.5,2124.8);
INSERT INTO foods(category_id, name, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES(3,'さばの塩焼き',500.0,10.1,18.0,7.3,8312.5,2124.8);
INSERT INTO foods(category_id, name, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES(3,'ロコモコ丼',500.0,10.1,18.0,7.3,8312.5,2124.8);
INSERT INTO foods(category_id, name, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES(3,'ビーガンの１２種の野菜カレー',500.0,10.1,18.0,7.3,8312.5,2124.8);
INSERT INTO foods(category_id, name, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES(3,'鶏の照り焼きスライス(目玉焼きのせ)',500.0,10.1,18.0,7.3,8312.5,2124.8);
INSERT INTO foods(category_id, name, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES(3,'さばの生姜煮',500.0,10.1,18.0,7.3,8312.5,2124.8);
INSERT INTO foods(category_id, name, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES(3,'牛丼(温玉付き)',500.0,10.1,18.0,7.3,8312.5,2124.8);
INSERT INTO foods(category_id, name, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES(3,'キーマカレー',500.0,10.1,18.0,7.3,8312.5,2124.8);
INSERT INTO foods(category_id, name, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES(3,'カレーハンバーグ',500.0,10.1,18.0,7.3,8312.5,2124.8);
INSERT INTO foods(category_id, name, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES(3,'ハッシュドビーフ',500.0,10.1,18.0,7.3,8312.5,2124.8);
INSERT INTO foods(category_id, name, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES(3,'柔らか鶏の照り焼き(目玉焼きのせ)',500.0,10.1,18.0,7.3,8312.5,2124.8);
INSERT INTO foods(category_id, name, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES(3,'カルビ丼(温玉付き)',500.0,10.1,18.0,7.3,8312.5,2124.8);
INSERT INTO foods(category_id, name, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES(3,'サラダボール',200.0,10.1,18.0,4.3,9312.5,4124.8);
INSERT INTO foods(category_id, name, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES(3,'たらこスパゲッティ',500.0,10.1,18.0,7.3,8312.5,2124.8);
INSERT INTO foods(category_id, name, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES(3,'ナポリタン',500.0,10.1,18.0,7.3,8312.5,2124.8);
INSERT INTO foods(category_id, name, kcal, carbohydrates, protein, lipid, vitamin, mineral) VALUES(3,'カルボナーラ',500.0,10.1,18.0,7.3,8312.5,2124.8);

Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 11, 21, 'ハマグリの酒蒸し', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 11, 21, 'わかめとツナの炒めもの', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 11, 21, 'レタスとシラスのサラダ', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 11, 21, '茄子とから揚げの味噌汁', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 11, 21, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 11, 22, 'お好み焼き', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 11, 22, '湯豆腐', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 11, 22, '野菜サラダ', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 11, 22, 'ごぼうと人参の味噌汁', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 11, 23, 'たらこスパゲティ', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 11, 23, 'きんぴらごぼう', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 11, 23, '野菜サラダ', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 11, 23, '豆腐とねぎの味噌汁', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 11, 24, '豚肉の生姜焼き', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 11, 24, '春菊と厚揚げの白和え', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 11, 24, 'トマトとチーズのサラダ', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 11, 24, 'ニラのかき卵スープ', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 11, 24, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 11, 25, 'メバルの煮つけ', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 11, 25, 'ホタルイカの沖漬け', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 11, 25, 'アスパラガスのサラダ', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 11, 25, '若竹汁', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 11, 25, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 11, 26, 'きびなごの天ぷら', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 11, 26, '茄子の甘酢かけ', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 11, 26, 'ささみときゅうりのサラダ', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 11, 26, 'しじみ汁', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 11, 26, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 11, 27, 'しめじと鶏肉の炊き込みご飯', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 11, 27, 'じゃがいもの明太子和え', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 11, 27, 'さつまいものサラダ', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 11, 27, '青梗菜と春雨のスープ', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 11, 28, '大根と厚揚げの中華煮', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 11, 28, '春菊の胡麻和え', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 11, 28, '水菜とちくわのサラダ', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 11, 28, 'ごぼうと小松菜の味噌汁', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 11, 28, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 12, 21, '焼き蟹', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 12, 21, 'ほうれん草とささみのお浸し', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 12, 21, 'かぶととレタスのサラダ', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 12, 21, '豚汁', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 12, 21, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 12, 22, '豚肉と白菜のミルフィーユ鍋', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 12, 22, 'にらの卵とじ', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 12, 22, '野菜サラダ', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 12, 22, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 12, 23, 'あさりのスープパスタ', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 12, 23, 'ごぼうとベーコンのコンソメ煮', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 12, 23, 'ツナとキャベツのサラダ', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 12, 23, 'コーンスープ', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 12, 24, '回鍋肉', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 12, 24, '春菊と厚揚げの白和え', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 12, 24, 'トマトとチーズのサラダ', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 12, 24, '豆腐の味噌汁', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 12, 24, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 12, 25, 'かつおの角煮', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 12, 25, '三つ葉とわかめのワサビ和え', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 12, 25, 'グリンアスパラのサラダ', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 12, 25, '生しいたけのスープ', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 12, 25, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 12, 26, 'きびなごの塩焼き', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 12, 26, '茄子の甘酢かけ', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 12, 26, 'トマトときゅうりのシーザーサラダ', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 12, 26, 'レタスのスープ', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 12, 26, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 12, 27, 'かつおの角煮', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 12, 27, '里芋のコロッケ', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 12, 27, 'ニンジンのサラダ', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 12, 27, 'じゃがいもの味噌汁', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 12, 27, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 12, 28, '牛肉と白菜のうま煮', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 12, 28, '春菊の胡麻和え', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 12, 28, '大根サラダ', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 12, 28, 'ごぼうと小松菜の味噌汁', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 12, 28, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 13, 21, '豆腐と高菜の炒め物', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 13, 21, '青梗菜の塩炒め', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 13, 21, 'レタスと韓国のりのサラダ', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 13, 21, 'えのきとザーサイのスープ', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 13, 21, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 13, 22, 'お好み焼き', 50, 10, 5, 500, 700, 'https://thumb.ac-illust.com/1e/1e10614defff49d1dd195b58cd29055b_w.jpeg');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 13, 22, '人参とちくわのきんぴら', 50, 10, 5, 500, 700, 'https://thumb.ac-illust.com/af/af1b4fa64d01e15b5ddcd2ea68efa6f2_t.jpeg');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 13, 22, 'ツナポテトサラダ', 50, 10, 5, 500, 700, 'https://www.illust-box.jp/db_img/sozai/00013/138292/watermark.jpg');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 13, 22, '豆腐とねぎの味噌汁', 50, 10, 5, 500, 700, 'https://4.bp.blogspot.com/-VtsRr-xjY00/Us_NcICBs8I/AAAAAAAAdJU/NNzOgC7bfWQ/s800/food_omisoshiru.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 13, 23, '和風あさりスパゲティ', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 13, 23, 'さつまいものはちみつバター', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 13, 23, 'きゃべつとベーコンのホットサラダ', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 13, 23, 'ブロッコリーのポタージュ', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 13, 24, 'イワシのカレー蒲焼', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 13, 24, '和風ポークビーンズ', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 13, 24, 'パンプキンサラダ', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 13, 24, '豆腐と椎茸のスープ', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 13, 24, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 13, 25, 'ひじきご飯', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 13, 25, '絹さやの卵とじ', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 13, 25, '厚揚げとサニーレタスのサラダ', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 13, 25, 'わかめの味噌汁', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 13, 26, 'ゴーヤの肉詰め煮', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 13, 26, '茄子と鶏肉のごま酢かけ', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 13, 26, 'パンプキンサラダ', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 13, 26, 'かぼちゃのポタージュ', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 13, 26, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 13, 27, 'サバのドレッシング漬け', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 13, 27, 'さつまいものはちみつバター', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 13, 27, 'おから入りタラモサラダ', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 13, 27, '粗汁', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 13, 27, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 13, 28, '鶏団子と白菜のくたくた煮', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 13, 28, 'ハムとほうれん草のクリーム和え', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 13, 28, '豚汁', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(01, 13, 28, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 11, 21, 'タラと白菜の和風煮', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 11, 21, 'かぶの梅肉醤油', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 11, 21, 'キャベツの浅漬け', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 11, 21, 'きのこの味噌汁', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 11, 21, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 11, 22, 'お好み焼き', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 11, 22, '湯豆腐', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 11, 22, '大根サラダ', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 11, 22, 'ジャガイモと玉ねぎの味噌汁', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 11, 23, 'サラダうどん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 11, 23, 'きんぴらごぼう', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 11, 23, 'タラモサラダ', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 11, 23, '豆腐とねぎの味噌汁', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 11, 24, '豚の冷しゃぶ', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 11, 24, 'かぼちゃの煮物', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 11, 24, '豆腐とじゃこのサラダ', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 11, 24, 'ニラと油揚げの味噌汁', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 11, 24, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 11, 25, 'わかめご飯', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 11, 25, '絹さやと油揚げのさっと煮', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 11, 25, 'レタスのしらすドレッシング', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 11, 25, 'クレソンの和風卵とじスープ', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 11, 26, 'きびなごの塩焼き', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 11, 26, 'イカとおくらの納豆和え', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 11, 26, 'パンプキンサラダ', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 11, 26, 'しじみ汁', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 11, 26, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 11, 27, '鮭のちゃんちゃん焼きうどん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 11, 27, '人参とトマトのサラダ', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 11, 27, '蒸しさつまいも', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 11, 27, 'じゃがいもの味噌汁', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 11, 28, '鰆の西京焼き', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 11, 28, 'ほうれん草の納豆和え', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 11, 28, '水菜とちくわのサラダ', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 11, 28, 'ごぼうと小松菜の味噌汁', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 11, 28, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 12, 21, 'タラと白菜の和風煮', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 12, 21, '大根と明太子和え', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 12, 21, '根菜とひじきの炒めサラダ', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 12, 21, 'わかめの澄まし汁', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 12, 21, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 12, 22, '豚肉と白菜のミルフィーユ鍋', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 12, 22, '湯豆腐', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 12, 22, '大根サラダ', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 12, 22, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 12, 23, 'ザーサイとねぎの汁素麺', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 12, 23, '切り干し大根の煮物', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 12, 23, 'トマトのサラダ', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 12, 23, 'わかめと油揚げの味噌汁', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 12, 24, 'ゆで豚の酢味噌', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 12, 24, 'かぼちゃの煮物', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 12, 24, 'トマトとチーズのサラダ', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 12, 24, '豆腐の味噌汁', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 12, 24, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');


Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 12, 25, '', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');

Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 12, 26, '茄子の味噌炒め', 50, 10, 5, 500, 700, 'https://thumb.ac-illust.com/9f/9fcf07dff2bee0d2acb9be6f7c537b46_t.jpeg');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 12, 26, 'イカとオクラの納豆和え', 50, 10, 5, 500, 700, 'https://illust.download/wp-content/uploads/download/food41Vp6.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 12, 26, 'パンプキンサラダ', 50, 10, 5, 500, 700, 'https://thumb.ac-illust.com/8b/8b39e642b1b1efb8b977d1b25023e8d7_w.jpeg');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 12, 26, 'しじみ汁', 50, 10, 5, 500, 700, 'https://thumb.ac-illust.com/94/94735cdfac2df859f96654ae56f1f6eb_t.jpeg');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 12, 26, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 12, 27, '白身魚のおろしレンコン煮', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 12, 27, 'じゃがいもの明太子和え', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 12, 27, '人参とトマトのサラダ', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 12, 27, 'とろろ汁', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 12, 27, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 12, 28, 'きんきの煮つけ', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 12, 28, 'せりの海苔和え', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 12, 28, '水菜とちくわのサラダ', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 12, 28, 'ごぼうと小松菜の味噌汁', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 12, 28, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 13, 21, 'ブロッコリー入り炒め豆腐', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 13, 21, 'きゃべつと椎茸の炒め物', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 13, 21, 'タラモサラダ', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 13, 21, 'わかめの味噌汁', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 13, 21, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 13, 22, 'お好み焼き', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 13, 22, '人参とちくわのきんぴら', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 13, 22, 'おかか入りツナポテトサラダ', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 13, 22, '豆腐とねぎの味噌汁', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 13, 23, '味噌ラーメン', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 13, 23, 'きんぴらごぼう', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 13, 23, 'タラモサラダ', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 13, 23, '豆腐とねぎの味噌汁', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 13, 24, '豚肉と茄子のゴマ炒め', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 13, 24, 'かぼちゃの煮物', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 13, 24, '豆腐とじゃこのサラダ', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 13, 24, '豆腐とねぎの味噌汁', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 13, 24, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 13, 25, '鯛の煮物', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 13, 25, 'ニラの卵とじ', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 13, 25, 'わかめの味噌汁', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 13, 25, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 13, 26, 'きびなごのから揚げ', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 13, 26, '揚げ茄子', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 13, 26, 'パンプキンサラダ', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 13, 26, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 13, 27, '鶏肉とレンコンの唐揚げ和風あんかけ', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 13, 27, '里芋の煮物', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 13, 27, 'タラモサラダ', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 13, 27, 'じゃがいもの味噌汁', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 13, 27, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 13, 28, 'ぶり大根', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 13, 28, 'ブロッコリーのツナ味噌炒め', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 13, 28, '豆腐とねぎの味噌汁', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(02, 13, 28, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(03, 11, 21, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(03, 11, 22, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(03, 11, 23, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(03, 11, 24, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(03, 11, 25, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(03, 11, 26, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(03, 11, 27, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(03, 11, 28, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(03, 12, 21, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(03, 12, 22, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(03, 12, 23, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(03, 12, 24, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(03, 12, 25, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(03, 12, 26, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(03, 12, 27, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(03, 12, 28, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(03, 13, 21, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(03, 13, 22, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(03, 13, 23, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(03, 13, 24, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(03, 13, 25, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(03, 13, 26, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(03, 13, 27, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(03, 13, 28, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(04, 11, 21, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(04, 11, 22, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(04, 11, 23, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(04, 11, 24, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(04, 11, 25, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(04, 11, 26, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(04, 11, 27, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(04, 11, 28, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(04, 12, 21, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(04, 12, 22, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(04, 12, 23, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(04, 12, 24, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(04, 12, 25, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(04, 12, 26, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(04, 12, 27, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(04, 12, 28, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(04, 13, 21, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(04, 13, 22, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(04, 13, 23, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(04, 13, 24, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(04, 13, 25, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(04, 13, 26, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(04, 13, 27, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
Insert into recommendation(genre, type, sort, name, carbohydrates, protein, lipid, vitamin, mineral,pic) VALUES(04, 13, 28, 'ごはん', 50, 10, 5, 500, 700, 'https://japaclip.com/files/rice-bowl.png');
